import { Injectable, computed, signal } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class DemoDataService {
  currentRole = signal<string>('admin');

  setRole(role: string): void {
    this.currentRole.set(role);
  }

  clinic = {
    id: 'demo-clinic-1',
    name: 'Clínica Veterinaria VetPro Demo',
    nit: '900.123.456-7',
    phone: '+57 601 234 5678',
    email: 'demo@vetpro.co',
    address: 'Cra 15 # 93-47, Chapinero',
    city: 'Bogotá',
    plan: 'pro' as const,
    aiMinutesUsed: 340,
    aiMinutesLimit: 600,
    logoUrl: undefined,
    createdAt: new Date('2024-01-15'),
  };

  patients = [
    {
      id: 'p1',
      clinicId: 'demo-clinic-1',
      tutorId: 't1',
      name: 'Toby',
      species: 'dog' as const,
      breed: 'Golden Retriever',
      sex: 'male' as const,
      sterilized: true,
      weight: 28,
      status: 'active' as const,
      birthDate: new Date('2019-03-12'),
      tutor: { firstName: 'Carlos', lastName: 'Martínez', phone: '3101234567', id: 't1', clinicId: 'demo-clinic-1', createdAt: new Date() },
      createdAt: new Date('2024-02-01'),
    },
    {
      id: 'p2',
      clinicId: 'demo-clinic-1',
      tutorId: 't2',
      name: 'Luna',
      species: 'cat' as const,
      breed: 'Siamés',
      sex: 'female' as const,
      sterilized: true,
      weight: 4.2,
      status: 'active' as const,
      birthDate: new Date('2021-07-08'),
      tutor: { firstName: 'Marcela', lastName: 'Rodríguez', phone: '3209876543', id: 't2', clinicId: 'demo-clinic-1', createdAt: new Date() },
      createdAt: new Date('2024-03-10'),
    },
    {
      id: 'p3',
      clinicId: 'demo-clinic-1',
      tutorId: 't3',
      name: 'Simón',
      species: 'dog' as const,
      breed: 'Beagle',
      sex: 'male' as const,
      sterilized: false,
      weight: 12,
      status: 'active' as const,
      birthDate: new Date('2020-11-23'),
      tutor: { firstName: 'Andrés', lastName: 'Gómez', phone: '3154567890', id: 't3', clinicId: 'demo-clinic-1', createdAt: new Date() },
      createdAt: new Date('2024-04-05'),
    },
    {
      id: 'p4',
      clinicId: 'demo-clinic-1',
      tutorId: 't4',
      name: 'Mia',
      species: 'cat' as const,
      breed: 'Persa',
      sex: 'female' as const,
      sterilized: true,
      weight: 3.8,
      status: 'active' as const,
      birthDate: new Date('2022-05-15'),
      tutor: { firstName: 'Valentina', lastName: 'Torres', phone: '3182345678', id: 't4', clinicId: 'demo-clinic-1', createdAt: new Date() },
      createdAt: new Date('2024-05-20'),
    },
    {
      id: 'p5',
      clinicId: 'demo-clinic-1',
      tutorId: 't5',
      name: 'Rocky',
      species: 'dog' as const,
      breed: 'Labrador Retriever',
      sex: 'male' as const,
      sterilized: true,
      weight: 32,
      status: 'active' as const,
      birthDate: new Date('2018-09-30'),
      tutor: { firstName: 'Jorge', lastName: 'Herrera', phone: '3167891234', id: 't5', clinicId: 'demo-clinic-1', createdAt: new Date() },
      createdAt: new Date('2024-06-08'),
    },
    {
      id: 'p6',
      clinicId: 'demo-clinic-1',
      tutorId: 't6',
      name: 'Cleo',
      species: 'cat' as const,
      breed: 'Angora',
      sex: 'female' as const,
      sterilized: false,
      weight: 3.5,
      status: 'active' as const,
      birthDate: new Date('2023-01-20'),
      tutor: { firstName: 'Sofía', lastName: 'Vargas', phone: '3103456789', id: 't6', clinicId: 'demo-clinic-1', createdAt: new Date() },
      createdAt: new Date('2024-07-15'),
    },
  ];

  appointments = [
    {
      id: 'a1',
      clinicId: 'demo-clinic-1',
      patientId: 'p1',
      vetId: 'v1',
      patient: this.patients[0],
      serviceType: 'Consulta general',
      scheduledAt: new Date(),
      durationMinutes: 30,
      status: 'waiting' as const,
      reason: 'Chequeo rutinario',
      createdAt: new Date(),
    },
    {
      id: 'a2',
      clinicId: 'demo-clinic-1',
      patientId: 'p2',
      vetId: 'v1',
      patient: this.patients[1],
      serviceType: 'Vacunación',
      scheduledAt: new Date(),
      durationMinutes: 20,
      status: 'in-progress' as const,
      reason: 'Rabia + Triple felina',
      createdAt: new Date(),
    },
    {
      id: 'a3',
      clinicId: 'demo-clinic-1',
      patientId: 'p3',
      vetId: 'v1',
      patient: this.patients[2],
      serviceType: 'Desparasitación',
      scheduledAt: new Date(),
      durationMinutes: 15,
      status: 'scheduled' as const,
      reason: 'Control trimestral',
      createdAt: new Date(),
    },
    {
      id: 'a4',
      clinicId: 'demo-clinic-1',
      patientId: 'p4',
      vetId: 'v1',
      patient: this.patients[3],
      serviceType: 'Cirugía',
      scheduledAt: new Date(),
      durationMinutes: 90,
      status: 'done' as const,
      reason: 'Esterilización',
      amountCharged: 350000,
      createdAt: new Date(),
    },
  ];

  walkers = [
    {
      id: 'w1',
      clinicId: 'demo-clinic-1',
      userId: 'u-walker-1',
      bio: 'Amante de los animales, 5 años de experiencia. Certificado en primeros auxilios para mascotas.',
      rating: 4.9,
      totalWalks: 312,
      pricePerHour: 35000,
      maxDogs: 3,
      coverageZones: ['Chapinero', 'Usaquén', 'Zona Rosa'],
      active: true,
      createdAt: new Date('2023-06-01'),
      user: {
        id: 'u-walker-1',
        clinicId: 'demo-clinic-1',
        firstName: 'Sebastián',
        lastName: 'Ospina',
        email: 'sebastian@vetpro.co',
        role: 'walker' as const,
        active: true,
        avatarUrl: undefined,
        branchId: null,
      },
      photoUrl: undefined,
    },
    {
      id: 'w2',
      clinicId: 'demo-clinic-1',
      userId: 'u-walker-2',
      bio: 'Estudiante de veterinaria, apasionada por el bienestar animal. Disponible fines de semana y tardes.',
      rating: 4.7,
      totalWalks: 87,
      pricePerHour: 30000,
      maxDogs: 2,
      coverageZones: ['Suba', 'Engativá', 'Fontibón'],
      active: true,
      createdAt: new Date('2024-01-10'),
      user: {
        id: 'u-walker-2',
        clinicId: 'demo-clinic-1',
        firstName: 'Daniela',
        lastName: 'Castillo',
        email: 'daniela@vetpro.co',
        role: 'walker' as const,
        active: true,
        avatarUrl: undefined,
        branchId: null,
      },
      photoUrl: undefined,
    },
  ];

  walkBookings = [
    {
      id: 'wb1',
      clinicId: 'demo-clinic-1',
      tutorId: 't1',
      walkerId: 'w1',
      patientIds: ['p1'],
      scheduledAt: new Date(),
      durationMins: 60,
      address: 'Cra 15 # 85-20, Chapinero, Bogotá',
      status: 'walking' as const,
      price: 35000,
      notes: 'Toby es amigable con otros perros',
      photos: [],
      createdAt: new Date(),
      tutor: { firstName: 'Carlos', lastName: 'Martínez', phone: '3101234567', id: 't1', clinicId: 'demo-clinic-1', createdAt: new Date() },
      walker: this.walkers[0],
    },
    {
      id: 'wb2',
      clinicId: 'demo-clinic-1',
      tutorId: 't5',
      walkerId: 'w1',
      patientIds: ['p5'],
      scheduledAt: new Date(Date.now() + 2 * 60 * 60 * 1000),
      durationMins: 45,
      address: 'Cl 100 # 14-55, Usaquén, Bogotá',
      status: 'assigned' as const,
      price: 35000,
      notes: 'Rocky puede ir suelto en el parque',
      photos: [],
      createdAt: new Date(),
      tutor: { firstName: 'Jorge', lastName: 'Herrera', phone: '3167891234', id: 't5', clinicId: 'demo-clinic-1', createdAt: new Date() },
      walker: this.walkers[0],
    },
    {
      id: 'wb3',
      clinicId: 'demo-clinic-1',
      tutorId: 't3',
      walkerId: 'w2',
      patientIds: ['p3'],
      scheduledAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
      durationMins: 30,
      address: 'Av Suba # 108-27, Suba, Bogotá',
      status: 'completed' as const,
      price: 30000,
      rating: 5,
      review: 'Excelente servicio, muy puntual',
      photos: [],
      createdAt: new Date(),
      tutor: { firstName: 'Andrés', lastName: 'Gómez', phone: '3154567890', id: 't3', clinicId: 'demo-clinic-1', createdAt: new Date() },
      walker: this.walkers[1],
    },
  ];

  stats = computed(() => ({
    totalPatients: 248,
    appointmentsToday: 12,
    pendingInvoices: 5,
    monthlyRevenue: 8450000,
  }));

  upcomingVaccines = [
    { patientName: 'Toby', vaccineName: 'Parvovirus + Distemper', dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000) },
    { patientName: 'Rocky', vaccineName: 'Rabia', dueDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000) },
    { patientName: 'Luna', vaccineName: 'Triple Felina', dueDate: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000) },
  ];
}
